spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: admin

  flyway:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    user: postgres
    password: admin
server:
  port: 8989